### ISSUE TITLE
feat(scope): Let package names being copied

### ISSUE THREAD

**Issue by santo998** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#765] opened 2024-12-23 06:48 UTC
### Describe the feature you want

Let package names being copied by double clicking them or right clicking them and displaying some menu, etc.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment] 2024-12-23 10:35
Duplicate of https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/49.

**Closed by AnonymousWP** 2024-12-23 10:35 UTC
Labels: enhancement
