### ISSUE TITLE
Overlays

### ISSUE THREAD

**Issue by Skizzy24** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#168] opened 2024-01-09 09:28 UTC
i suggest to move all overlays in expert section, they arent a thing to play with and can cause bootloop if removed, also i don't think removing them will improve performance or battery life.

**Comment by AnonymousWP** [comment] 2024-01-10 19:18
Are you sure that *all* can cause a bootloop or only a selection?

**Comment by AnonymousWP** [comment] 2024-02-15 08:57
@Skizzy24 Please follow-up on this, or else it'll be closed.

**Comment by AnonymousWP** [comment] 2024-03-06 10:35
Closing this because it's not a bug and you've used the incorrect issue template. Also, you did not follow up.

**Closed by AnonymousWP** 2024-03-06 10:35 UTC
Labels: bug
