### ISSUE TITLE
send `adb kill-server` when user exit the app

### ISSUE THREAD

**Issue by Obegg** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#177] opened 2024-01-14 20:54 UTC
**Describe the feature you want**
send a `adb kill-server` command to the phone via ADB when user exit the app therefor will close the process `adb.exe` from remaining open while app is not used.

**Comment by prakharb5** [comment] 2024-01-26 17:11
If not as a default setting, keeping it as an option in setting would be great!

**Comment by AnonymousWP** [comment] 2024-03-06 10:40
Duplicate of https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/67.

**Closed by AnonymousWP** 2024-03-06 10:40 UTC
Labels: enhancement
