### ISSUE TITLE
bug(uad-list): app in the list (json) are installed on the cell phone but do not appear in UAD

### ISSUE THREAD

**Issue by vitoramaral10** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#361] opened 2024-03-18 18:18 UTC
### Describe the bug

I ended up opening 3 issues because I thought they weren't on the list (my mistake for not seeing the json, sorry), but they don't appear in the UAD for removal from the cell phone

https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/357
https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/358
https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/359

Mi device is: Xiaomi Redmi 10 5G
Android 14 with HyperOS

### Expected behavior

The expectation was that they would show up to uninstall

### Provide logs

2024-03-18 15:17:35 DEBUG [src\core\update.rs:174] Checking for UAD-ng update
2024-03-18 15:17:35 INFO  [src\gui\views\list.rs:136] -----------------------------------------------------------------
2024-03-18 15:17:35 INFO  [src\gui\views\list.rs:137] ANDROID_SDK: 34 | DEVICE: Redmi 22041219NY
2024-03-18 15:17:35 INFO  [src\gui\views\list.rs:141] -----------------------------------------------------------------

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment] 2024-03-18 18:35
So you're saying they don't appear at all or do you mean that they can't be uninstalled?

**Comment by vitoramaral10** [comment] 2024-03-18 18:54
it simply doesn't appear, even setting all filters to all

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/7594095/61b2d45d-8750-4330-b987-8ac06a90b450)

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/7594095/e35c354d-408a-474f-ae63-14c37e5b537c)

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/7594095/38f30fcf-28e8-4137-ae83-4d27ba4735bb)

**Comment by AnonymousWP** [comment] 2024-03-18 19:00
I see, but this is a duplicate of https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/82. You checked the checkbox "This issue is not a duplicate of an existing bug report." but apparently you didn't check. 😉 We can continue there.

**Closed by AnonymousWP** 2024-03-18 19:00 UTC
Labels: bug
