### ISSUE TITLE
bug(scope): macOS Monterey 12.7.6 - MacBook Pro (Intel) - error upgrading 1.0.3 -> 1.1.0

### ISSUE THREAD

**Issue by CodeBreakerOO7** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#695] opened 2024-10-20 12:12 UTC
### Describe the bug

ERROR [src/gui/mod.rs:320] Failed to update UAD-ng: Bad CPU type in execAlso installing direct (and chmod 755) gives the same error. Probably only compiled for Silicon architecture, not Intel.

### Expected behavior

Flawless upgrade to 1.1.0

### You have a solution?

Compile (or tell the bot) to create an universal executable (Intel + Arm-Silicon) for macOS or create two different for each architecture

### Operating System

MacOS

### Distro version

Monterey 12.6.7

### Provide logs

<details><summary>Log</summary>

```
ERROR [src/gui/mod.rs:320] Failed to update UAD-ng: Bad CPU type in executable (os error 86)
</details>


### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Frigyes06** [comment] 2024-11-26 07:50
Duplicate of #722
Closing this because other issue has more discussion.

**Closed** 2024-11-26 07:51 UTC
Labels: bug, duplicate
