### ISSUE TITLE
feat(search): add possibility to search for descriptions

### ISSUE THREAD

**Issue by Rudxain** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#647] opened 2024-09-23 21:52 UTC
### Describe the feature you want

- 0x192/universal-android-debloater#134
- #640

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment] 2024-10-04 12:43
This is a duplicate of https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/184 it seems.

**Closed by AnonymousWP** 2024-10-04 12:43 UTC
Labels: enhancement, UI
