### ISSUE TITLE
bug(scope): Apps supposedly listed as recommended don't appear in the list (tiktok, facebook...)

### ISSUE THREAD

**Issue by vaccarov** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#658] opened 2024-09-27 13:57 UTC
### Describe the bug

Hello all,

First let me thank all the community for this tool and for the maintenance.

I'd like to submit what i think is a bug, indeed after full debloat of recommended apps, I still have apps that [should have been listed](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/blob/main/resources/assets/uad_lists.json) but don't show in the GUI, just a couple of examples:

```
tiktok: com.zhiliaoapp.musically
amazon music: com.amazon.mp3
booking: com.booking
...
```

Also, some obvious bloatware do not appear in uad_lists.json, for example here is one:
```
aliexpress: com.alibaba.aliexpresshd
```

My device is a Poco M6 pro (2312fpca6g), last update (hyperos 1.0.5.0 UNFMIXM)

Let me know if anything else is needed, I'd be happy to help !

### Expected behavior

Apps listed in uad_lists should appear in the GUI

### You have a solution?

Manual uninstallation from phone

### Operating System

MacOS

### Distro version

14.6.1

### Provide logs

<details><summary>Log</summary>

```
2024-09-27 14:24:50 ERROR [src/core/config.rs:92] Invalid config file: `TOML parse error at line 1, column 1
  |
1 | [general]
  | ^^^^^^^^^
missing field `backup_folder`
`
2024-09-27 14:24:50 ERROR [src/core/config.rs:96] Restoring default config file
2024-09-27 14:24:51 DEBUG [src/core/update.rs:183] Checking for UAD-ng update
2024-09-27 14:24:52 INFO  [src/gui/views/list.rs:160] -----------------------------------------------------------------
2024-09-27 14:24:52 INFO  [src/gui/views/list.rs:161] ANDROID_SDK: 33 | DEVICE: POCO 2312FPCA6G
2024-09-27 14:24:52 INFO  [src/gui/views/list.rs:165] -----------------------------------------------------------------
2024-09-27 14:24:59 DEBUG [src/core/update.rs:204] Failed to check UAD-ng update
2024-09-27 14:25:37 DEBUG [src/core/config.rs:80] config: New device settings saved
2024-09-27 14:25:45 DEBUG [src/core/update.rs:183] Checking for UAD-ng update
2024-09-27 14:25:47 INFO  [src/gui/views/list.rs:160] -----------------------------------------------------------------
2024-09-27 14:25:47 INFO  [src/gui/views/list.rs:161] ANDROID_SDK: 33 | DEVICE: POCO 2312FPCA6G
2024-09-27 14:25:47 INFO  [src/gui/views/list.rs:165] -----------------------------------------------------------------
2024-09-27 14:25:53 DEBUG [src/core/update.rs:204] Failed to check UAD-ng update
2024-09-27 14:27:53 DEBUG [src/core/update.rs:183] Checking for UAD-ng update
2024-09-27 14:27:53 INFO  [src/gui/views/list.rs:160] -----------------------------------------------------------------
2024-09-27 14:27:53 INFO  [src/gui/views/list.rs:161] ANDROID_SDK: 33 | DEVICE: POCO 2312FPCA6G
2024-09-27 14:27:53 INFO  [src/gui/views/list.rs:165] -----------------------------------------------------------------
2024-09-27 14:28:01 DEBUG [src/core/update.rs:204] Failed to check UAD-ng update
2024-09-27 14:57:14 INFO  [src/gui/views/list.rs:160] -----------------------------------------------------------------
2024-09-27 14:57:14 INFO  [src/gui/views/list.rs:161] ANDROID_SDK: 34 | DEVICE: POCO 2312FPCA6G
2024-09-27 14:57:14 INFO  [src/gui/views/list.rs:165] -----------------------------------------------------------------
2024-09-27 15:17:14 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.hotwordenrollment.xgoogle -> Success
2024-09-27 15:17:14 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 android.autoinstalls.config.Xiaomi.model -> Success
2024-09-27 15:17:14 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.calllogbackup -> Success
2024-09-27 15:17:14 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.hotwordenrollment.okgoogle -> Success
2024-09-27 15:17:14 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.inputsettings.overlay.miui -> Success
2024-09-27 15:17:14 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.managedprovisioning.overlay -> Success
2024-09-27 15:17:14 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.egg -> Success
2024-09-27 15:17:14 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.bluetoothmidiservice -> Success
2024-09-27 15:17:15 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.microdroid.empty_payload -> Success
2024-09-27 15:17:15 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.overlay.gmscontactprovider -> Success
2024-09-27 15:17:16 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.overlay.gmssettingprovider -> Success
2024-09-27 15:17:16 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.overlay.gmssettings -> Success
2024-09-27 15:17:17 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.overlay.gmstelecomm -> Success
2024-09-27 15:17:17 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.overlay.gmstelephony -> Success
2024-09-27 15:17:18 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.providers.partnerbookmarks -> Success
2024-09-27 15:17:18 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.rkpdapp -> Success
2024-09-27 15:17:18 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.role.notes.enabled -> Success
2024-09-27 15:17:18 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.settings.overlay.miui -> Success
2024-09-27 15:17:18 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.stk.overlay.miui -> Success
2024-09-27 15:17:18 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.systemui.accessibility.accessibilitymenu -> Success
2024-09-27 15:17:19 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.systemui.overlay.miui -> Success
2024-09-27 15:17:19 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.theme.font.notoserifsource -> Success
2024-09-27 15:17:19 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.traceur -> Success
2024-09-27 15:17:19 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.android.virtualmachine.res -> Success
2024-09-27 15:17:19 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.debug.loggerui -> Success
2024-09-27 15:17:20 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.facebook.appmanager -> Success
2024-09-27 15:17:20 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.facebook.services -> Success
2024-09-27 15:17:20 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.facebook.system -> Success
2024-09-27 15:17:20 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.fingerprints.optical -> Success
2024-09-27 15:17:20 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.goodix.fingerprint.setting -> Success
2024-09-27 15:17:21 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.ambient.streaming -> Success
2024-09-27 15:17:21 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.accessibility.switchaccess -> Success
2024-09-27 15:17:21 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.adservices.api -> Success
2024-09-27 15:17:21 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.apps.docs -> Success
2024-09-27 15:17:22 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.apps.healthdata -> Success
2024-09-27 15:17:22 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.apps.maps -> Success
2024-09-27 15:17:22 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.apps.photos -> Success
2024-09-27 15:17:22 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.apps.restore -> Success
2024-09-27 15:17:22 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.apps.safetyhub -> Success
2024-09-27 15:17:23 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.apps.subscriptions.red -> Success
2024-09-27 15:17:23 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.apps.tachyon -> Success
2024-09-27 15:17:23 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.apps.turbo -> Success
2024-09-27 15:17:23 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.apps.youtube.music -> Success
2024-09-27 15:17:24 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.as.oss -> Success
2024-09-27 15:17:24 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.cellbroadcastreceiver.overlay.miui -> Success
2024-09-27 15:17:24 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.cellbroadcastservice.overlay.miui -> Success
2024-09-27 15:17:24 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.federatedcompute -> Success
2024-09-27 15:17:24 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.feedback -> Success
2024-09-27 15:17:24 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.gm -> Success
2024-09-27 15:17:24 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.gms.location.history -> Success
2024-09-27 15:17:25 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.marvin.talkback -> Success
2024-09-27 15:17:25 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.ondevicepersonalization.services -> Success
2024-09-27 15:17:25 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.onetimeinitializer -> Success
2024-09-27 15:17:25 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.overlay.gmsconfig.asi -> Success
2024-09-27 15:17:25 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.overlay.gmsconfig.common -> Success
2024-09-27 15:17:25 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.overlay.gmsconfig.comms -> Success
2024-09-27 15:17:25 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.overlay.gmsconfig.geotz -> Success
2024-09-27 15:17:26 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.overlay.gmsconfig.personalsafety -> Success
2024-09-27 15:17:26 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.overlay.healthconnect -> Success
2024-09-27 15:17:26 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.overlay.modules.captiveportallogin.forframework -> Success
2024-09-27 15:17:26 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.overlay.modules.documentsui -> Success
2024-09-27 15:17:26 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.overlay.modules.modulemetadata.forframework -> Success
2024-09-27 15:17:26 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.overlay.modules.permissioncontroller -> Success
2024-09-27 15:17:26 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.overlay.modules.permissioncontroller.forframework -> Success
2024-09-27 15:17:26 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.projection.gearhead -> Success
2024-09-27 15:17:27 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.safetycenter.resources -> Success
2024-09-27 15:17:27 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.videos -> Success
2024-09-27 15:17:27 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.android.youtube -> Success
2024-09-27 15:17:27 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.google.mainline.adservices -> Success
2024-09-27 15:17:27 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.huaqin.diaglogger -> Success
2024-09-27 15:17:28 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.huaqin.sarcontroller -> Success
2024-09-27 15:17:28 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.huaqin.factory -> Success
2024-09-27 15:17:28 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mediatek.callrecorder -> Success
2024-09-27 15:17:28 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mediatek.engineermode -> Success
2024-09-27 15:17:28 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mediatek.gbaservice -> Success
2024-09-27 15:17:28 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mediatek.lbs.em2.ui -> Success
2024-09-27 15:17:29 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mediatek.mdmlsample -> Success
2024-09-27 15:17:29 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mediatek.mdmconfig -> Success
2024-09-27 15:17:29 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mediatek.miravision.ui -> Success
2024-09-27 15:17:29 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mediatek.MtkSettingsResOverlay -> Success
2024-09-27 15:17:29 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mediatek.SettingsProviderResOverlay -> Success
2024-09-27 15:17:29 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mediatek.voicecommand -> Success
2024-09-27 15:17:30 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mediatek.voiceunlock -> Success
2024-09-27 15:17:30 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mediatek.ygps -> Success
2024-09-27 15:17:30 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mi.AutoTest -> Success
2024-09-27 15:17:30 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mi.globalbrowser -> Success
2024-09-27 15:17:30 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mi.globalminusscreen -> Success
2024-09-27 15:17:30 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.mi.healthglobal -> Success
2024-09-27 15:17:30 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.analytics -> Success
2024-09-27 15:17:31 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.backup -> Success
2024-09-27 15:17:31 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.bugreport -> Success
2024-09-27 15:17:31 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.cleaner -> Success
2024-09-27 15:17:31 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.cloudbackup -> Success
2024-09-27 15:17:31 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.cloudservice -> Success
2024-09-27 15:17:32 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.daemon -> Success
2024-09-27 15:17:32 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.fm -> Success
2024-09-27 15:17:32 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.fmservice -> Success
2024-09-27 15:17:32 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.micloudsync -> Success
2024-09-27 15:17:32 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.miservice -> Success
2024-09-27 15:17:33 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.miwallpaper.overlay -> Success
2024-09-27 15:17:33 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.miwallpaper.overlay.customize -> Success
2024-09-27 15:17:33 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.msa.global -> Success
2024-09-27 15:17:33 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.phone.carriers.overlay.h3g -> Success
2024-09-27 15:17:33 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.phone.carriers.overlay.vodafone -> Success
2024-09-27 15:17:33 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.phrase -> Success
2024-09-27 15:17:34 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.player -> Success
2024-09-27 15:17:35 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.qr -> Success
2024-09-27 15:17:35 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.settings.rro.device.hide.statusbar.overlay -> Success
2024-09-27 15:17:35 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.settings.rro.device.type.overlay -> Success
2024-09-27 15:17:35 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.system.overlay -> Success
2024-09-27 15:17:36 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.videoplayer -> Success
2024-09-27 15:17:36 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.wallpaper.overlay -> Success
2024-09-27 15:17:36 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.wallpaper.overlay.customize -> Success
2024-09-27 15:17:36 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miui.yellowpage -> Success
2024-09-27 15:17:37 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.miuix.editor -> Success
2024-09-27 15:17:37 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.modemdebug -> Success
2024-09-27 15:17:37 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.tencent.soter.soterserver -> Success
2024-09-27 15:17:37 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.wdstechnology.android.kryten -> Success
2024-09-27 15:17:37 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.xiaomi.aicr -> Success
2024-09-27 15:17:37 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.xiaomi.barrage -> Success
2024-09-27 15:17:37 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.xiaomi.calendar -> Success
2024-09-27 15:17:37 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.xiaomi.cameratools -> Success
2024-09-27 15:17:38 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.xiaomi.glgm -> Success
2024-09-27 15:17:38 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.xiaomi.mi_connect_service -> Success
2024-09-27 15:17:38 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.xiaomi.mipicks -> Success
2024-09-27 15:17:38 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.xiaomi.mtb -> Success
2024-09-27 15:17:38 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.xiaomi.payment -> Success
2024-09-27 15:17:38 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.xiaomi.simactivate.service -> Success
2024-09-27 15:17:39 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.xiaomi.trustservice -> Success
2024-09-27 15:17:39 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 com.xiaomi.xmsfkeeper -> Success
2024-09-27 15:17:39 INFO  [src/core/sync.rs:131] [Recommended] pm uninstall --user 0 org.ifaa.aidl.manager -> Success
2024-09-27 15:17:56 INFO  [src/gui/views/list.rs:160] -----------------------------------------------------------------
2024-09-27 15:17:56 INFO  [src/gui/views/list.rs:161] ANDROID_SDK: 34 | DEVICE: POCO 2312FPCA6G
2024-09-27 15:17:56 INFO  [src/gui/views/list.rs:165] -----------------------------------------------------------------
2024-09-27 15:28:33 INFO  [src/core/sync.rs:131] [Advanced] pm uninstall --user 0 com.android.sharedstoragebackup -> Success
2024-09-27 15:28:33 INFO  [src/core/sync.rs:131] [Advanced] pm uninstall --user 0 com.miui.mediaviewer -> Success
2024-09-27 15:28:34 INFO  [src/core/sync.rs:131] [Advanced] pm uninstall --user 0 com.miui.gallery -> Success
2024-09-27 15:28:34 INFO  [src/core/sync.rs:131] [Advanced] pm uninstall --user 0 com.google.android.partnersetup -> Success
2024-09-27 15:28:34 INFO  [src/core/sync.rs:131] [Advanced] pm uninstall --user 0 com.miui.global.packageinstaller -> Success
2024-09-27 15:28:34 INFO  [src/core/sync.rs:131] [Advanced] pm uninstall --user 0 com.android.providers.downloads.ui -> Success
2024-09-27 15:28:34 INFO  [src/core/sync.rs:131] [Advanced] pm uninstall --user 0 com.google.android.printservice.recommendation -> Success
2024-09-27 15:28:34 INFO  [src/core/sync.rs:131] [Advanced] pm uninstall --user 0 android.miui.poco.launcher.res -> Success
2024-09-27 15:28:34 INFO  [src/core/sync.rs:131] [Advanced] pm uninstall --user 0 com.xiaomi.account -> Success
2024-09-27 15:28:49 INFO  [src/gui/views/list.rs:160] -----------------------------------------------------------------
2024-09-27 15:28:49 INFO  [src/gui/views/list.rs:161] ANDROID_SDK: 34 | DEVICE: POCO 2312FPCA6G
2024-09-27 15:28:49 INFO  [src/gui/views/list.rs:165] -----------------------------------------------------------------
```
</details>

### Acknowledgements

- [x] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Rudxain** [comment] 2024-09-29 20:56
https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/592#issuecomment-2352138951

**Comment by Rudxain** [comment] 2024-09-29 21:03
I'm closing this as dupe. But thank you anyways!

If anyone believes this isn't a dupe of #592, please let me know

**Closed by Rudxain** 2024-09-29 21:03 UTC
Labels: bug
