### ISSUE TITLE
pm uninstall "Package name" -> Failure [DELETE_FAILED_INTERNAL_ERROR]

### ISSUE THREAD

**Issue by sheeshman3** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#263] opened 2024-02-15 08:52 UTC
trying to uninstall any packages from the program causes this error to appear in the log files pm uninstall "Package name" -> Failure [DELETE_FAILED_INTERNAL_ERROR], all though uninstalling it manually from the powershell dosent generate that error, i think there is an error with the way its trying to uninstall it, i have to type "pm uninstall --user 0 "Package name" for it to work, but in the logs it dosent include the user and the number, and also it cant update to newer version, installing it from the github dosent update it to a newer version

**Comment by AnonymousWP** [comment] 2024-02-15 08:54
Duplicate of https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/251.

**Closed by AnonymousWP** 2024-02-15 08:54 UTC
Labels: bug
